# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kui(object):
    def setupUi(self, Kui):
        Kui.setObjectName("Kui")
        Kui.resize(646, 476)
        self.CheckBox = CheckBox(Kui)
        self.CheckBox.setGeometry(QtCore.QRect(40, 180, 93, 22))
        self.CheckBox.setObjectName("CheckBox")
        self.CheckBox_2 = CheckBox(Kui)
        self.CheckBox_2.setGeometry(QtCore.QRect(40, 210, 93, 22))
        self.CheckBox_2.setObjectName("CheckBox_2")
        self.ComboBox = ComboBox(Kui)
        self.ComboBox.setGeometry(QtCore.QRect(50, 250, 77, 32))
        self.ComboBox.setObjectName("ComboBox")

        self.retranslateUi(Kui)
        QtCore.QMetaObject.connectSlotsByName(Kui)

    def retranslateUi(self, Kui):
        _translate = QtCore.QCoreApplication.translate
        Kui.setWindowTitle(_translate("Kui", "Form"))
        self.CheckBox.setText(_translate("Kui", "Check box"))
        self.CheckBox_2.setText(_translate("Kui", "Check box"))
from qfluentwidgets import CheckBox, ComboBox
