# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect

from ETO.Mui import ScrollableMovableGridPixmapWidget

class Ui_Pui(object):
    def setupUi(self, Pui):
        Pui.setObjectName("Pui")
        Pui.resize(420, 420)

        self.gridLayout = QtWidgets.QGridLayout(Pui)
        self.gridLayout.setObjectName("gridLayout")

        self.StateToolTip = ScrollableMovableGridPixmapWidget(4, 4, 420, False)
        self.StateToolTip.setObjectName('ScrollableMovableGridPixmapWidget')
        self.StateToolTip.setGeometry(QRect(0, 0, 420, 420))

        self.gridLayout.addWidget(self.StateToolTip, 0, 0, 1, 1)

        self.retranslateUi(Pui)
        QtCore.QMetaObject.connectSlotsByName(Pui)

    def retranslateUi(self, Pui):
        _translate = QtCore.QCoreApplication.translate
        Pui.setWindowTitle(_translate("Pui", "Form"))
from qfluentwidgets import HorizontalFlipView, SimpleCardWidget
